name: Basic CI

#triggers
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

#jobs
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .Net
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore WeatherAPI/WeatherAPI.csproj

      - name: Build
        run: dotnet build WeatherAPI/WeatherAPI.csproj --no-restore --configuration Release

      - name: Display build
        run: |
          echo "Build completed successfully."
          echo "Build time: $(date)"
          dotnet --version